# Generated by Django 6.1.1 on 2026-09-05 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'PO Received'), ('PARSING', 'Parsing Document'), ('PARSED', 'Parsed & Ready for Quote'), ('QUOTED', 'Quote Generated'), ('JOB_CREATED', 'Job Created'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=20)),
                ('po_file', models.FileField(blank=True, null=True, upload_to='purchase_orders/%Y/%m/')),
                ('raw_email_sender', models.EmailField(blank=True, max_length=254)),
                ('raw_email_subject', models.CharField(blank=True, max_length=500)),
                ('raw_email_body', models.TextField(blank=True)),
                ('pickup_location', models.TextField(blank=True)),
                ('delivery_location', models.TextField(blank=True)),
                ('cargo_description', models.TextField(blank=True)),
                ('weight_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_pallets', models.PositiveIntegerField(blank=True, null=True)),
                ('required_pickup_date', models.DateField(blank=True, null=True)),
                ('required_delivery_date', models.DateField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
