# Generated by Django 6.1.1 on 2026-09-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_purchaseorder_extracted_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='source',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('MANUAL_UPLOAD', 'Manual Upload')], db_index=True, default='EMAIL', max_length=20),
        ),
    ]
