# Generated by Django 6.1.1 on 2026-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_purchaseorder_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='acknowledgment_sent',
            field=models.BooleanField(default=False, help_text='Indicates whether the automated no-reply receipt confirmation was dispatched.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='acknowledgment_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the automated no-reply receipt confirmation was sent.', null=True),
        ),
    ]
