# Generated by Django 6.1.1 on 2026-09-08 19:28

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_purchaseorder_acknowledgment_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='Unique RFC Message-ID, Brevo item token, or content hash for strict idempotency', max_length=255, unique=True)),
                ('sender_email', models.EmailField(db_index=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, default='', max_length=200)),
                ('recipient_email', models.EmailField(default='orders@menardtrading.com', max_length=254)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Processing Failed')], db_index=True, default='RECEIVED', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'Inbound Email Message',
                'verbose_name_plural': 'Inbound Email Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueueMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(default='no-reply', max_length=50)),
                ('recipient_list', models.JSONField(default=list, help_text='List of recipient email addresses')),
                ('reply_to', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('template_name', models.CharField(max_length=200)),
                ('context_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('attachments_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Delivery Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=4)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_emails', to='orders.purchaseorder')),
                ('inbound_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_emails', to='orders.inboundemailmessage')),
            ],
            options={
                'verbose_name': 'Queued Email Message',
                'verbose_name_plural': 'Queued Email Messages',
                'ordering': ['next_attempt_at', 'created_at'],
            },
        ),
    ]
