# Generated by Django 6.1.1 on 2026-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_inboundemailmessage_emailqueuemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
