# Generated by Django 6.1.1 on 2026-09-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_logisticsjob_created_at_and_more'),
        ('orders', '0007_purchaseorder_accepted_at_purchaseorder_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='logistics.logisticsjob'),
        ),
    ]
