# Generated by Django 6.1.1 on 2026-09-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_purchaseorder_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supporting_attachment',
            field=models.FileField(blank=True, null=True, upload_to='purchase_order_supporting/%Y/%m/'),
        ),
    ]
