# Generated by Django 6.1.1 on 2026-09-16 08:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_purchaseorder_supporting_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.CharField(max_length=100)),
                ('recipient', models.EmailField(max_length=254)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('attachment_manifest', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating Document'), ('ATTACHMENT_FAILED', 'Attachment Validation Failed'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=25)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
