# Generated by Django 6.1.1 on 2026-09-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField()),
                ('billing_address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(choices=[('100_UPFRONT', '100% Upfront'), ('50_DEPOSIT_50_POD', '50% Deposit / 50% on POD'), ('30_DEPOSIT_70_POD', '30% Deposit / 70% on POD'), ('30_DAYS_NET', '30 Days Net'), ('CUSTOM', 'Custom Terms')], default='50_DEPOSIT_50_POD', max_length=30)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['company_name'],
            },
        ),
    ]
