# Generated by Django 6.1.1 on 2026-09-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTermOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable term name, e.g. 50% Deposit / 50% on Delivery', max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Machine identifier, e.g. 50_DEPOSIT_50_POD', max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Term Option',
                'verbose_name_plural': 'Payment Term Options',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, default='50_DEPOSIT_50_POD', max_length=150),
        ),
    ]
