# Generated by Django 6.1.1 on 2026-09-06 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email_otp_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='MENARD TRADING CC', help_text='Official business/company name', max_length=200)),
                ('tagline', models.CharField(blank=True, default='ALWAYS ON TIME', help_text='Corporate tagline', max_length=200)),
                ('postal_address', models.CharField(blank=True, default='P O BOX 497-19001,', help_text='Postal address', max_length=255)),
                ('physical_address', models.TextField(blank=True, default='', help_text='Street address / Logistics depot location')),
                ('city', models.CharField(blank=True, default='RUNDU', help_text='City / Town', max_length=100)),
                ('country', models.CharField(blank=True, default='NAMIBIA', help_text='Country', max_length=100)),
                ('vat_number', models.CharField(blank=True, default='', help_text='Official VAT Registration Number', max_length=100)),
                ('company_reg_number', models.CharField(blank=True, default='', help_text='Company / Close Corporation Registration Number', max_length=100)),
                ('phone', models.CharField(blank=True, default='', help_text='Primary telephone number', max_length=50)),
                ('mobile', models.CharField(blank=True, default='', help_text='Direct / Mobile number', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@menardtrading.com', help_text='General company email', max_length=254)),
                ('orders_email', models.EmailField(blank=True, default='orders@menardtrading.com', help_text='Orders & POs mailbox', max_length=254)),
                ('quotes_email', models.EmailField(blank=True, default='quotes@menardtrading.com', help_text='Quotations mailbox', max_length=254)),
                ('accounts_email', models.EmailField(blank=True, default='accounts@menardtrading.com', help_text='Accounts & Billing mailbox', max_length=254)),
                ('website', models.URLField(blank=True, default='https://menardtrading.com', help_text='Official company website URL')),
                ('logo_image', models.ImageField(blank=True, help_text='Custom company logo image', null=True, upload_to='branding/')),
                ('bank_name', models.CharField(blank=True, default='', help_text='Bank name (e.g. First National Bank)', max_length=100)),
                ('account_name', models.CharField(blank=True, default='', help_text='Bank account holder name', max_length=150)),
                ('account_number', models.CharField(blank=True, default='', help_text='Bank account number', max_length=60)),
                ('account_type', models.CharField(blank=True, default='', help_text='Account type (e.g. Business Cheque Account)', max_length=60)),
                ('branch_code', models.CharField(blank=True, default='', help_text='Bank branch code', max_length=30)),
                ('branch_name', models.CharField(blank=True, default='', help_text='Branch name', max_length=100)),
                ('swift_code', models.CharField(blank=True, default='', help_text='SWIFT / BIC code', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
