# Generated by Django 6.1.1 on 2026-09-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='login_bg_image_1',
            field=models.ImageField(blank=True, help_text='Login & Portal Background Image 1', null=True, upload_to='branding/backgrounds/'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='login_bg_image_2',
            field=models.ImageField(blank=True, help_text='Login & Portal Background Image 2', null=True, upload_to='branding/backgrounds/'),
        ),
    ]
