# Generated by Django 6.1.1 on 2026-09-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_companysettings_login_bg_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='login_bg_image_3',
            field=models.ImageField(blank=True, help_text='Login & Portal Background Image 3', null=True, upload_to='branding/backgrounds/'),
        ),
    ]
