# Generated by Django 6.1.1 on 2026-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_companysettings_login_bg_image_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('NEW_ORDER', 'New Purchase Order'), ('EMAIL_FAILED', 'Email Delivery Failed'), ('QUOTE_APPROVED', 'Quote Approved'), ('PAYMENT_RECEIVED', 'Payment Received'), ('SYSTEM', 'System Alert')], db_index=True, default='NEW_ORDER', max_length=30)),
                ('link_url', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
