# Generated by Django 6.1.1 on 2026-09-08 21:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Default VAT Rate Percentage (e.g. 15.00, 0, 10)', max_digits=5),
        ),
    ]
