# Generated by Django 6.1.1 on 2026-09-09 13:44

from decimal import Decimal
from django.db import migrations, models


def update_support_email(apps, schema_editor):
    CompanySettings = apps.get_model('accounts', 'CompanySettings')
    for cs in CompanySettings.objects.all():
        if cs.email == 'info@menardtrading.com' or not cs.email:
            cs.email = 'support@menardtrading.com'
            cs.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_companysettings_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company_reg_number',
            field=models.CharField(blank=True, default='CC/2022/03892', help_text='Company / Close Corporation Registration Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(blank=True, default='support@menardtrading.com', help_text='General company email', max_length=254),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='mobile',
            field=models.CharField(blank=True, default='+264 81 445 5188', help_text='Direct / Mobile number', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, default='+264 81 445 5188', help_text='Primary telephone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='vat_number',
            field=models.CharField(blank=True, default='13009715-11', help_text='Official Tax / VAT Registration Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default VAT Rate Percentage (e.g. 15.00, 0, 10)', max_digits=5),
        ),
        migrations.RunPython(update_support_email, migrations.RunPython.noop),
    ]
