# Generated by Django 6.1.1 on 2026-09-05 07:11

import apps.billing.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('logistics', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, default=apps.billing.models.generate_invoice_number, max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('FULL', 'Full 100% Tax Invoice'), ('PARTIAL_DEPOSIT', 'Mobilization / Deposit Invoice'), ('PARTIAL_BALANCE', 'Final Balance on POD Invoice'), ('ADD_ON', 'Supplementary / Add-on Invoice (Demurrage/Tolls)')], db_index=True, default='FULL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued / Sent'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('notes', models.TextField(blank=True, default='Payment strictly according to agreed terms. Direct EFT into Menard Trading CC bank account.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='logistics.logisticsjob')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='quotes.quotation')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, default=apps.billing.models.generate_receipt_number, max_length=50, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('EFT_BANK_TRANSFER', 'EFT / Bank Transfer'), ('CREDIT_CARD', 'Credit / Debit Card'), ('DIRECT_DEPOSIT', 'Direct Bank Deposit'), ('CASH', 'Cash')], default='EFT_BANK_TRANSFER', max_length=30)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_reference', models.CharField(help_text='e.g. Bank Statement Reference or POP Code', max_length=100)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='customers.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
