# Generated by Django 6.1.1 on 2026-09-11 08:47

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('FULL', 'Standard Full Invoice'), ('PARTIAL_DEPOSIT', 'Mobilization / Deposit Invoice'), ('PARTIAL_BALANCE', 'Final Balance on POD Invoice'), ('ADD_ON', 'Supplementary / Add-on Invoice (Demurrage/Tolls)')], db_index=True, default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
