# Generated by Django 6.1.1 on 2026-09-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_created_at_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference_number',
            field=models.CharField(blank=True, default='', help_text='Editable originating PO or document reference number.', max_length=100),
        ),
    ]
