# Generated by Django 6.1.1 on 2026-09-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_terms_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
