# Generated by Django 6.1.1 on 2026-09-06 04:43

import apps.accounting.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('payment_terms', models.CharField(default='30_DAYS_NET', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor / Supplier',
                'verbose_name_plural': 'Vendors / Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(db_index=True, default=apps.accounting.models.generate_bill_number, max_length=50, unique=True)),
                ('supplier_reference', models.CharField(blank=True, help_text="Supplier's original invoice/bill number", max_length=100)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('due_date', models.DateField(db_index=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Received / Awaiting Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void')], db_index=True, default='ISSUED', max_length=20)),
                ('bill_pdf', models.FileField(blank=True, null=True, upload_to='supplier_bills/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounting.vendor')),
            ],
            options={
                'verbose_name': 'Supplier Bill (Accounts Payable)',
                'verbose_name_plural': 'Supplier Bills (Accounts Payable)',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(db_index=True, default=apps.accounting.models.generate_bill_payment_number, max_length=50, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('EFT_BANK_TRANSFER', 'EFT / Bank Transfer'), ('CREDIT_CARD', 'Credit / Debit Card'), ('DIRECT_DEPOSIT', 'Direct Bank Deposit'), ('CASH', 'Cash')], default='EFT_BANK_TRANSFER', max_length=30)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.supplierbill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(db_index=True, default=apps.accounting.models.generate_expense_number, max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('payee', models.CharField(blank=True, help_text='Direct payee name if not a registered vendor', max_length=255)),
                ('description', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('EFT_BANK_TRANSFER', 'EFT / Bank Transfer'), ('CREDIT_CARD', 'Credit / Debit Card'), ('DIRECT_DEPOSIT', 'Direct Bank Deposit'), ('CASH', 'Cash'), ('PETTY_CASH', 'Petty Cash')], default='EFT_BANK_TRANSFER', max_length=30)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending Approval'), ('DRAFT', 'Draft'), ('VOID', 'Void / Cancelled')], db_index=True, default='PAID', max_length=20)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.expensecategory')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.vendor')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
