# Generated by Django 6.1.1 on 2026-09-05 07:11

import apps.logistics.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(db_index=True, default=apps.logistics.models.generate_job_number, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked / Scheduled'), ('DISPATCHED', 'Dispatched / En Route to Pickup'), ('IN_TRANSIT', 'Loaded & In Transit'), ('DELIVERED', 'Delivered at Bay'), ('POD_RECEIVED', 'POD Signed & Verified'), ('CLOSED', 'Job Closed')], db_index=True, default='BOOKED', max_length=20)),
                ('vehicle_registration', models.CharField(blank=True, help_text='e.g. CA 123-456', max_length=50)),
                ('trailer_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('driver_phone', models.CharField(blank=True, max_length=50)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('cargo_summary', models.TextField(blank=True)),
                ('weight_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scheduled_date', models.DateField(default=django.utils.timezone.now)),
                ('dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('pod_document', models.FileField(blank=True, null=True, upload_to='pods/%Y/%m/')),
                ('pod_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_jobs', to='customers.customer')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='quotes.quotation')),
            ],
            options={
                'verbose_name': 'Logistics Job',
                'verbose_name_plural': 'Logistics Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
