# Generated by Django 6.1.1 on 2026-09-11 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logisticsjob',
            name='scheduled_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
