# Generated by Django 6.1.1 on 2026-09-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quotation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='reference_number',
            field=models.CharField(blank=True, default='', help_text='Editable client PO or other originating reference number.', max_length=100),
        ),
    ]
